---
title: "Tarea_Cuestionario Introducción a la Estadística"
author: "Roberto Coto Guevara"
date: "`r Sys.Date()`"
output: 
  prettydoc::html_pretty:
    theme: cayman
    toc: yes
---

# Titulo 
Cuestionario de deserción académica

# Introducción
El presente cuestionario tiene como propósito recopilar información relacionada con los principales factores que influyen en la deserción académica de los estudiantes universitarios.

**Propósito del cuestionario:** Identificar motivos y circunstancias que influyen en el abandono de estudios.

**Importancia del estudio:** Contribuir a la mejora de estrategias institucionales que reduzcan la deserción.

**Instrucciones para los participantes:** Responder de forma clara, objetiva y sincera a cada una de las preguntas.

**Confidencialidad y uso de datos:** La información se usará únicamente con fines académicos y será tratada de forma confidencial.

# Población Meta
**Características demográficas:** Estudiantes universitarios entre 18 y 35 años.

**Criterios de inclusión:** Estudiantes que han interrumpido al menos un ciclo lectivo.

**Criterios de exclusión:** Estudiantes que abandonaron por traslado a otra universidad.

**Tamaño estimado de la población:** 50 participantes.


# Objetivo General

Establecer los factores principales que inciden en la deserción académica de los estudiantes universitarios y analizar su impacto en la continuidad de los estudios.

# Formulario 
<https://forms.office.com/r/2KcaU6fqgi?origin=lprLink>


Prueba 
